[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
